language: java

jobs:
  include:
  - stage: test
    before_install:
    - echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
    after_success:
    - ./gradlew jacocoTestReport coveralls

  - stage: snapshot
    env:
    - VERSION_SCOPE='-SNAPSHOT'
    before_install:
    - echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
    script: ./gradlew uploadArchives -x check

  - stage: release
    env:
    - VERSION_SCOPE=''
    before_install:
    - echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
    script: ./gradlew uploadArchives -x check

stages:
- name: test
- name: snapshot
  if: branch IN (master, bugfix)
- name: release
  if: branch = release
