language: java
sudo: false
dist: trusty

jobs:
  include:
  - stage: test
    install: skip
    script:
    - echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
    - ./gradlew -Dorg.gradle.project.signing.keyId="$SIGNING_KEYID" -Dorg.gradle.project.signing.password="$SIGNING_PASSWORD" -Dorg.gradle.project.signing.secretKeyRingFile="$SIGNING_SECRETKEYRINGFILE" check build
    - ./gradlew -Dorg.gradle.project.signing.keyId="$SIGNING_KEYID" -Dorg.gradle.project.signing.password="$SIGNING_PASSWORD" -Dorg.gradle.project.signing.secretKeyRingFile="$SIGNING_SECRETKEYRINGFILE" jacocoTestReport coveralls

  - stage: snapshot
    install: skip
    env:
    - VERSION_SCOPE='-SNAPSHOT'
    script:
    - echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
    - ./gradlew -Dorg.gradle.project.signing.keyId="$SIGNING_KEYID" -Dorg.gradle.project.signing.password="$SIGNING_PASSWORD" -Dorg.gradle.project.signing.secretKeyRingFile="$SIGNING_SECRETKEYRINGFILE" build uploadArchives -x check

  - stage: release
    install: skip
    env:
    - VERSION_SCOPE=''
    script:
    - echo $GPG_KEY | base64 --decode > ${SIGNING_SECRETKEYRINGFILE}
    - ./gradlew -Dorg.gradle.project.signing.keyId="$SIGNING_KEYID" -Dorg.gradle.project.signing.password="$SIGNING_PASSWORD" -Dorg.gradle.project.signing.secretKeyRingFile="$SIGNING_SECRETKEYRINGFILE" build uploadArchives -x check
#    on:
#      tags: true

stages:
- name: test
- name: snapshot
  if: branch IN (master, bugfix)
- name: release
  if: branch = release
